# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(default=django.utils.timezone.now, verbose_name=True),
            preserve_default=False,
        ),
    ]
