# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_in_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='in_print',
        ),
    ]
